CREATE TABLE stcav1.Chat (idChat BIGINT AUTO_INCREMENT NOT NULL, Comunidad_idComunidad BIGINT NOT NULL, Estampa DATETIME NOT NULL, Mensaje LONGTEXT, Usuario_idUsuario BIGINT NOT NULL, PRIMARY KEY (idChat))
CREATE TABLE stcav1.Comentario_Tablon (idComentario_Tablon BIGINT AUTO_INCREMENT NOT NULL, Estampa DATETIME NOT NULL, Mensaje VARCHAR(255), Tablon_idTablon BIGINT NOT NULL, Usuario_idUsuario BIGINT NOT NULL, PRIMARY KEY (idComentario_Tablon))
CREATE TABLE stcav1.Comunidad (idComunidad BIGINT AUTO_INCREMENT NOT NULL, Descripcion LONGTEXT, Nombre VARCHAR(255), Tematica VARCHAR(35), PRIMARY KEY (idComunidad))
CREATE TABLE stcav1.Comunidad_has_Contenido (Contenido_idContenido BIGINT NOT NULL, Comunidad_idComunidad BIGINT NOT NULL, PRIMARY KEY (Contenido_idContenido, Comunidad_idComunidad))
CREATE TABLE stcav1.Comunidad_has_Etiquetas (Etiquetas_idEtiquetas BIGINT NOT NULL, Comunidad_idComunidad BIGINT NOT NULL, PRIMARY KEY (Etiquetas_idEtiquetas, Comunidad_idComunidad))
CREATE TABLE stcav1.Contenido (idContenido BIGINT AUTO_INCREMENT NOT NULL, Descriptor LONGTEXT, Duracion DOUBLE, Estado VARCHAR(13), Fecha_creacion DATETIME, Fuente VARCHAR(255), Ruta_fuente LONGTEXT, Ruta_screenshot LONGTEXT, Sinopsis LONGTEXT, Titulo VARCHAR(255), Usuario_idUsuario BIGINT NOT NULL, PRIMARY KEY (idContenido))
CREATE TABLE stcav1.Contenido_has_Etiquetas (Contenido_idContenido BIGINT NOT NULL, Etiquetas_idEtiquetas BIGINT NOT NULL, PRIMARY KEY (Contenido_idContenido, Etiquetas_idEtiquetas))
CREATE TABLE stcav1.Etiquetas (idEtiquetas BIGINT AUTO_INCREMENT NOT NULL, Nombre VARCHAR(255), PRIMARY KEY (idEtiquetas))
CREATE TABLE stcav1.Evento (idEvento BIGINT AUTO_INCREMENT NOT NULL, Descripcion LONGTEXT, Descriptor LONGTEXT, Duracion DECIMAL(17,3), Estado VARCHAR(13), Fecha_creacion DATE, Nombre VARCHAR(255), Programa_idPrograma BIGINT NOT NULL, Ruta LONGTEXT, PRIMARY KEY (idEvento))
CREATE TABLE stcav1.Info_Asociada (idInfo_Asociada BIGINT AUTO_INCREMENT NOT NULL, Duracion INTEGER, Evento_idEvento BIGINT NOT NULL, Texto LONGTEXT, Tiempo_despliegue INTEGER, PRIMARY KEY (idInfo_Asociada))
CREATE TABLE stcav1.Intereses (idIntereses BIGINT AUTO_INCREMENT NOT NULL, Nombre VARCHAR(255), PRIMARY KEY (idIntereses))
CREATE TABLE stcav1.Intereses_has_Usuario (Usuario_idUsuario BIGINT NOT NULL, Intereses_idIntereses BIGINT NOT NULL, PRIMARY KEY (Usuario_idUsuario, Intereses_idIntereses))
CREATE TABLE stcav1.Noticia (idNoticia BIGINT AUTO_INCREMENT NOT NULL, Comunidad_idComunidad BIGINT NOT NULL, Id_notificacion BIGINT, Texto VARCHAR(255), Tipo_Noticia_idTipo_Noticia BIGINT NOT NULL, PRIMARY KEY (idNoticia))
CREATE TABLE stcav1.Notificado (Noticia_idNoticia BIGINT NOT NULL, Usuario_idUsuario BIGINT NOT NULL, PRIMARY KEY (Noticia_idNoticia, Usuario_idUsuario))
CREATE TABLE stcav1.Preferencias_Programas (Favorito SMALLINT NOT NULL, Recordatorio SMALLINT, Programa_idPrograma BIGINT NOT NULL, Usuario_idUsuario BIGINT NOT NULL, PRIMARY KEY (Programa_idPrograma, Usuario_idUsuario))
CREATE TABLE stcav1.Profesion (idProfesion BIGINT AUTO_INCREMENT NOT NULL, Nombre VARCHAR(255) NOT NULL, PRIMARY KEY (idProfesion))
CREATE TABLE stcav1.Programa (idPrograma BIGINT AUTO_INCREMENT NOT NULL, Comunidad_idComunidad BIGINT NOT NULL, Descripcion LONGTEXT, Dia VARCHAR(2), Hora TIME, Nombre VARCHAR(255), Ruta_screenshot LONGTEXT, PRIMARY KEY (idPrograma))
CREATE TABLE stcav1.Tablon (idTablon BIGINT AUTO_INCREMENT NOT NULL, Comunidad_idComunidad BIGINT NOT NULL, Estampa DATETIME NOT NULL, Foto LONGTEXT, Mensaje VARCHAR(255), Usuario_idUsuario BIGINT NOT NULL, PRIMARY KEY (idTablon))
CREATE TABLE stcav1.Tipo_Noticia (idTipo_Noticia BIGINT AUTO_INCREMENT NOT NULL, Descripcion VARCHAR(255), PRIMARY KEY (idTipo_Noticia))
CREATE TABLE stcav1.Usuario (idUsuario BIGINT AUTO_INCREMENT NOT NULL, Direccion VARCHAR(255), Email VARCHAR(255), Fecha_nacimiento DATE, Foto LONGTEXT, Genero VARCHAR(255), Login VARCHAR(255) NOT NULL, Nombres VARCHAR(255), Pwd VARCHAR(255), PRIMARY KEY (idUsuario))
CREATE TABLE stcav1.Usuario_has_Comunidad (Rol VARCHAR(11) NOT NULL, Usuario_idUsuario BIGINT NOT NULL, Comunidad_idComunidad BIGINT NOT NULL, PRIMARY KEY (Usuario_idUsuario, Comunidad_idComunidad))
CREATE TABLE stcav1.Usuario_has_Profesion (Profesion_idProfesion BIGINT NOT NULL, Usuario_idUsuario BIGINT NOT NULL, PRIMARY KEY (Profesion_idProfesion, Usuario_idUsuario))
CREATE TABLE stcav1.Valoracion (idValoracion BIGINT AUTO_INCREMENT NOT NULL, Evento_idEvento BIGINT NOT NULL, Texto LONGTEXT, PRIMARY KEY (idValoracion))
CREATE TABLE stcav1.Votacion (idVotacion BIGINT AUTO_INCREMENT NOT NULL, Respuesta VARCHAR(2), Valoracion_idValoracion BIGINT NOT NULL, PRIMARY KEY (idVotacion))
